name: Backfill season (generate daily bulletins)

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: "Start date (YYYY-MM-DD)"
        required: true
        default: "2024-12-01"
      end_date:
        description: "End date (YYYY-MM-DD)"
        required: true
        default: "2025-04-30"

jobs:
  backfill:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: Europe/Zurich

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r bulletin/requirements.txt

      - name: Build history
        run: |
          python scripts/backfill.py "${{ github.event.inputs.start_date }}" "${{ github.event.inputs.end_date }}"

      - name: Debug: list public dir
        run: |
          echo "===== ls -R public ====="
          ls -R public || true

      - name: Upload public dir artifact
        uses: actions/upload-artifact@v4
        with:
          name: backfill-public
          path: public

      - name: Publish to gh-pages (under /history/)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages